"""add author foreignkey to books

Revision ID: 004
Revises: 003
Create Date: 2021-08-25 20:31:57.912869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_books_author_id'), 'books', ['author_id'], unique=False)
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_author_id'), table_name='books')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
